# Numpy Advance

In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

In [2]:
print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 3)
2
6


In [3]:
my_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [4]:
print(my_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
reshaped_arr = my_arr.reshape(2, 3, -1)
print(reshaped_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
reshaped_arr = my_arr.reshape(-1)
print(reshaped_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
for i in reshaped_arr:
    print(i, end=" | ")

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 

In [8]:
reshaped_arr = reshaped_arr.reshape(2,6)
print(reshaped_arr)
for i in reshaped_arr:
    print(i, end='|')

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[1 2 3 4 5 6]|[ 7  8  9 10 11 12]|

In [13]:
for i in np.nditer(reshaped_arr):
    print(i, end='|')
type(reshaped_arr)

1|2|3|4|5|6|7|8|9|10|11|12|

numpy.ndarray

In [12]:
np.__version__

'1.26.1'